### ISSUE TITLE
syzscope plugin

### ISSUE THREAD

**Issue by peng-hui** [seclab-ucr/SyzBridge#3]
Dear @plummm,

Thanks for making SyzBrdige open-source, and I find the framework really helpful. I was trying the syzscope plugin in the current SyzBridge framework, but unfortunately, I did not succeed. Have you tested the syzscope plugin?

- I installed the SyzBridge in a docker running Ubuntu 18.04 and used Python 3.8 as required. 
- I used the https://github.com/plummm/SyzScope/blob/master/tutorial/examples/WARNING_held_lock_freed.md example with commit a8d38d1b68ffc744c53bd9b9fc1dbd6c86b1afe2.
- I executed the command `python3.8 syzbridge run --syz-feature-minimize --syzscope`
- SyzFeatureMinimize produced expected results.
- `symbolic_execution.log-*` show  `SyzScope does not support current gdb, please change to pwndbg in ~/.gdbinit`, but  `gdb.log-*` look like the correct pwndbg is used.

Look forward to your response! 

Thank you!
Penghui

**Comment by plummm** [comment]
Hi, syzscope require pwndbg, it's installed during `python3.8 syzbridge build --all`.
if you already ran this command, can you make sure `tools/.stamp/SETUP_PWNDBG` exist in your environment?

**Comment by plummm** [comment]
`2024-02-19 06:50:11,012  Exception occurred: version: future feature annotations is not defined (unicorn.py, line 2) (<class 'SyntaxError'>)`. Can you show me the version of your gdb from `gdb -v`?

**Comment by plummm** [comment]
Thanks for the image. The gdb in your docker image is out-of-date, I'll build an official docker image as soon as possible

**Comment by plummm** [comment]
I've tested with gdb 12.1, it works fine. Try to upgrade to a newer version gdb.
