### ISSUE TITLE
Potential concurrency issue in syzbridge/syzscope

### ISSUE THREAD

**Issue by peng-hui** [seclab-ucr/SyzBridge#4]
Hi @plummm, I encountered another issue that might be related to concurrency. However, I did not figure out the cause to deterministically reproduce it. I checked the code of `pwnlib/term/term.py` and it seemed the error was about read/write from sys.stdout.  The error occurs frequently, especially after a failed execution. Have you ever experienced similar issues?

```sh
BlockingIOError: [Errno 11] write could not complete without blocking
```
<img width="947" alt="屏幕截图 2024-02-27 151420" src="https://github.com/seclab-ucr/SyzBridge/assets/35496882/ff2f58f7-446e-423e-8f45-07282bf5a71e">

or 
```sh
BlockingIOError: [Errno 11] resource temporarily unavailable
```
<img width="913" alt="屏幕截图 2024-02-27 151435" src="https://github.com/seclab-ucr/SyzBridge/assets/35496882/4ef883b8-68a3-4c8b-8d91-9746412b9d40">

**Comment by plummm** [comment]
Hi, I believe this is an issue related to the docker environment. I have encountered such issue only in docker, the root cause remains unknown for now. After I deployed SyzBridge on the host machine, this issue was gone.
