### ISSUE TITLE
Bug in enable/disable configs

### ISSUE THREAD

**Issue by peng-hui** [seclab-ucr/SyzBridge#5]
Recent commits for enabling/disabling certain configs contain a bug that would unexpectedly change the config crawled from syzbot. This bug could result in failures in starting the kernel due to unexpected kenerl configs.

1. syzbridge/plugins/\_\_init\_\_.py writes enable_config and disable_config files with at least a line of "\n".
```python
with open(os.path.join(self.path_case, 'enable_config'), 'w') as f:
    f.writelines(config_enable)
    f.write('\n') <- bug?
    f.truncate()
with open(os.path.join(self.path_case, 'disable_config'), 'w') as f:
    f.writelines(config_disable)
    f.write('\n') <- bug?
    f.truncate()
```

2. syzbridge/scripts/deploy-linux.sh always calls config_enable() and config_disable() for at least once given the "\n" in the files. 
```sh
if [ -f "$CASE_PATH/enable_config" ]; then
  cat $CASE_PATH/enable_config |
  while read -r line; do \
      config_enable $line; \ <- always get executed once with empty $line/$key
  done
fi

if [ -f "$CASE_PATH/disable_config" ]; then
  cat $CASE_PATH/disable_config |
  while read -r line; do \
      config_disable $line; \ <- always get executed once with empty $line/$key
  done
fi
```
3. the following code would replace with an empty $key, i.e., "sed -i "s/=n/#  is not set/g" to unset configs. 
```sh
function config_disable() {
  key=$1
  sed -i "s/$key=n/# $key is not set/g" .config
  sed -i "s/$key=m/# $key is not set/g" .config
  sed -i "s/$key=y/# $key is not set/g" .config
  grep $key .config || echo "# $key is not set" >> .config
}
function config_enable() {
  key=$1
  sed -i "s/$key=n/$key=y/g" .config
  sed -i "s/$key=m/$key=y/g" .config
  sed -i "s/# $key is not set/$key=y/g" .config
  grep $key .config || echo "$key=y" >> .config
}

```
4. removing the two lines of ` f.write('\n')` fixes this issue.

**Comment by plummm** [comment]
Much appreciated. Removing these two lines may result in other issues. The last line in enable_config/disable_config will be ignored in `deploy_linux.sh`. https://github.com/seclab-ucr/SyzBridge/commit/87d37d23aeea27ff7aa64a7535b45cf462d9497a fix this problem.
