### ISSUE TITLE
Cralwer bug in obtaining syz repro

### ISSUE THREAD

**Issue by peng-hui** [seclab-ucr/SyzBridge#6]
Dear @plummm,

Thanks for open-sourcing the great tool. I recently found a crawler bug in obtaining the syz.repro from syzbot (which did work previously), perhaps due to the recent updates of syzbot. The following code would raise an exception and could not retrieve the URL of syz.repro. 

https://github.com/seclab-ucr/SyzBridge/blob/2edef07443a55096896935c759644425a1b88d49/syzbridge/modules/syzbot/syzbotCrawler.py#L757

A temporary fix would be 
```py
syz_repro = syzbot_host_url + repros[2].next.next.attrs['href'] 
```

**Comment by plummm** [comment]
Can you provide the command you ran, along with the case id from syzbot?

**Comment by plummm** [comment]
Fixed it in the latest commit.
